spring:
  application:
    name: "Record shop"
    message: "Welcome to the Record Shop"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/recordShop?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SleepyDjYawns1!
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    properties:
      temp:
        use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.MySQLDialect