spring:
  application:
    name: "Record shop"
    message: "Welcome to the Record Shop"
  datasource:
    url: jdbc:mysql://localhost:3306/recordShop?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:  ${MY_SQL_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl